/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_colin_jni_Main */

#ifndef _Included_com_colin_jni_Main
#define _Included_com_colin_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_colin_jni_Main
 * Method:    getPassWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_colin_jni_Main_getPassWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
